name: flutter_counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  english_words: ^4.0.0
  bip39: ^1.0.4
  convert: ^3.0.1
  #freezed_annotation: ^0.12.0
  meta: ^1.2.4
  pedantic: ^1.9.0
  pointycastle: ^2.0.1
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.6
  uri: ^1.0.0
  json_annotation: ^4.0.1
  retrofit: ^2.0.1
  logger: any
  flutter_html: ^2.1.1

dev_dependencies:
  build_runner: ^2.1.1
  retrofit_generator:  2.0.1
  #freezed: ^0.12.6
  json_serializable: ^4.1.4
  #test: ^1.15.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.1"

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  adaptive_icon_background: "#2C2321"
  ios: true